{% set name = "textual" %}
{% set version = "0.88.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual-{{ version }}.tar.gz
  sha256: 9c56d953dc7d1a8ddf06acc910d9224027e02416551f92920e70f435bd28e062

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.1,<4.0
    - poetry-core >=1.2.0
    - pip
  run:
    - typing_extensions >=4.4.0,<5.0.0
    - platformdirs >=3.6.0,<5
    - python >=3.8.1,<4.0.0
    - markdown-it-py >=2.1.0
    - linkify-it-py >=1,<3
    - mdit-py-plugins
    - rich >=13.3.3
    - typing-extensions >=4.4.0,<5.0.0
  run_constrained:
    - tree-sitter >=0.20.1,<0.21.0
    - tree_sitter_languages =1.10.2

test:
  imports:
    - textual
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_file: LICENSE
  summary: Modern Text User Interface framework
  dev_url: https://github.com/Textualize/textual
  doc_url: https://textual.textualize.io

extra:
  recipe-maintainers:
    - davidbrochart
    - carlodri
    - xhochy
