{% set name = "textual" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b86d4668a072fc85092f081e157e1e7575b353b2f6b728755752bbbe23123063

build:
  number: 1
  noarch: python


outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
      noarch: python
    requirements:
      host:
        - python >=3.7,<4
        - poetry-core >=1.0.0
        - pip
      run:
        - python >=3.7,<4
        - rich >12.6
        - markdown-it-py >=2.1.0,<2.2
        - typing-extensions >=4.4,<4.5
        - importlib-metadata >=4.11.3,<4.12
    test:
      imports:
        - textual
        - textual.layouts
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-devtools
    build:
      script: echo Nothing to do.
      noarch: python
      entry_points:
        - textual = textual.cli.cli:run
    requirements:
      host:
        - python >=3.7,<4
        - poetry-core >=1.0.0
        - pip
      run:
        - python >=3.7,<4
        - {{ pin_subpackage('textual', exact=True) }}
        - aiohttp >=3.8.1
        - click >=8.1.2
        - msgpack-python >=1.0.3
        - mkdocs-exclude >=1.0.2,<1.1
    test:
      commands:
        - textual --help

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Textual is a TUI (Text User Interface) framework for Python inspired by modern web development.
  dev_url: https://github.com/Textualize/textual
  doc_url: https://textual.textualize.io/

extra:
  recipe-maintainers:
    - carlodri
    - davidbrochart
