{% set name = "textual" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 277407ab1beee474420ae76fb77dbe4c284300a124132907f786764da6b12f6f

build:
  number: 0
  noarch: python


outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --no-build-isolation -vv
      noarch: python
    requirements:
      host:
        - python >=3.7,<4
        - poetry-core >=1.0.0
        - pip
      run:
        - python >=3.7,<4
        - rich >=13.3.3
        - markdown-it-py >=2.2,<3
        - typing-extensions >=4.4,<4.5
        - importlib-metadata >=4.11.3
    test:
      imports:
        - textual
        - textual.layouts
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-devtools
    build:
      noarch: python
      entry_points:
        - textual = textual.cli.cli:run
    requirements:
      host:
        - python >=3.7,<4
        - poetry-core >=1.0.0
        - pip
      run:
        - python >=3.7,<4
        - {{ pin_subpackage('textual', exact=True) }}
        - aiohttp >=3.8.1
        - click >=8.1.2
        - msgpack-python >=1.0.3
        - mkdocs-exclude >=1.0.2,<1.1
    test:
      imports:
        - textual.app
        - textual.reactive
        - textual.widget
      commands:
        - textual --help

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern Text User Interface framework.
  dev_url: https://github.com/Textualize/textual
  doc_url: https://textual.textualize.io/

extra:
  recipe-maintainers:
    - davidbrochart
    - carlodri
